# Request

int32 row
int32 col
uint16[] agent_cells # cells which contain agents
uint16[] hostile_cells # cells which contain hostiles
uint8[]  world # grid as array

---

# Response
char[] plan # plan of steps to take
int32 moves # number of moves in array